# Generated by Django 4.0.3 on 2022-04-03 17:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ER_Base_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=30)),
                ('memo', models.CharField(max_length=100)),
                ('remove_password', models.CharField(max_length=4, validators=[django.core.validators.MinLengthValidator(4)])),
                ('most_pick', models.JSONField(default='{}')),
                ('winning_rate', models.FloatField()),
                ('averageKills', models.FloatField()),
                ('averageHunts', models.FloatField()),
                ('averageAssistants', models.FloatField()),
                ('soloTier', models.CharField(max_length=10)),
                ('duoTier', models.CharField(max_length=10)),
                ('squadTier', models.CharField(max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
