# Generated by Django 4.0.3 on 2022-04-02 10:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ER_Char_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charname', models.CharField(max_length=30)),
                ('char_winning_rate', models.FloatField()),
                ('char_Kills', models.FloatField()),
                ('char_Hunts', models.FloatField()),
                ('char_Assistants', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ER_Base_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=30)),
                ('memo', models.CharField(max_length=100)),
                ('remove_password', models.CharField(max_length=4, validators=[django.core.validators.MinLengthValidator(4)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('winning_rate', models.FloatField()),
                ('averageKills', models.FloatField()),
                ('averageHunts', models.FloatField()),
                ('averageAssistants', models.FloatField()),
                ('soloTier', models.CharField(max_length=10)),
                ('duoTier', models.CharField(max_length=10)),
                ('squadTier', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('most_pick', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Re_API.er_char_status')),
            ],
        ),
    ]
