# Generated by Django 4.0.3 on 2022-04-05 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Re_API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ER_Trolls_Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=30)),
                ('ven_count', models.IntegerField(default=0)),
                ('memo', models.CharField(max_length=50)),
                ('trolls_ven', models.BooleanField(default=False)),
            ],
        ),
    ]
